# -*- coding: utf-8 -*-
"""temp.ipynb

Automatically generated by Colaboratory.

Original file is located atg
    https://colab.research.google.com/drive/1mWKp7jKLasemHoXOlSdvLUD1-nsyQoHU
"""



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import streamlit as st
from PIL import Image

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Capstone


Suhu_Jakarta = pd.read_excel('Suhu Jakarta.xlsx')

#Suhu_Jakarta['Tahun'] = Suhu_Jakarta['Tanggal'].str.slice(6,9)

Suhu_Jakarta['Tanggal'] = pd.to_datetime(Suhu_Jakarta['Tanggal'].astype(str), format = '%d-%m-%Y')

st.set_page_config(page_title=None, page_icon=None, layout="wide")

header_image = Image.open("cuaca.jpeg")
header_image = header_image.resize((1050, 400))
st.markdown("<h1 style = 'text-align : center; color : white; font_size : 40 px; font-family : Arial'><b>Heatwave di Jakarta?<b></h1>", unsafe_allow_html= True)
st.image(header_image,  use_column_width=False)

st.write("Beredar informasi yang menyebutkan bahwa Jakarta akan dilanda cuaca ekstrem. Disebut-sebut, suhu akan menjadi sangat panas bahkan mencapai 50 derajat celcius.")

st.write("Bagaimana faktanya?")

st.write("Menurut data dari BMKG (Badan Meteorologi, Klimatologi dan Geofisika) dari tahun 2008 sampai dengan 2023, suhu rata2 dan suhu maksimum di Jakarta selama 15 tahun terakhir ini tidak mengalami kenaikan yang signifikan. Sedangkan untuk suhu minimum Jakarta selama 15 tahun mengalami sedikit kenaikan.")


fig1= plt.figure(figsize = (15,7))
sns.lineplot(data=Suhu_Jakarta, x="Tanggal", y="Suhu_Rata2")
#st.pyplot(fig1)

fig2= plt.figure(figsize = (15,7))
sns.lineplot(data=Suhu_Jakarta, x="Tanggal", y="Suhu_Minimum")
#st.pyplot(fig2)

fig3= plt.figure(figsize = (15,7))
sns.lineplot(data=Suhu_Jakarta, x="Tanggal", y="Suhu_Maksimum")
#st.pyplot(fig3)

options = ['Suhu Rata2', 'Suhu Minimum', 'Suhu Maksimum']
factor_group = st.selectbox("Suhu", options, key="factor_group")
if factor_group == 'Suhu Rata2':
    st.pyplot(fig1)
    st.caption("")
elif factor_group == 'Suhu Minimum':
    st.pyplot(fig2)
    st.caption("")
elif factor_group == 'Suhu Maksimum':
    st.pyplot(fig3)
    st.caption("")

st.write("Apakah saja faktor yang mempengaruhi cuaca suatu wilayah?")
st.write("1.	Suhu udara")
st.write("2.	Penyinaran matahari")
st.write("3.	Kelembaban udara")
st.write("4.	Kecepatan angin")

fig4= plt.figure(figsize = (15,7))

sns.heatmap(Suhu_Jakarta.corr(),
            annot = True, cmap ='RdYlGn', vmin = -1, vmax = 1, linewidths = 0.5)
plt.show()
st.pyplot(fig4)

st.write("Lantas apakah Jakarta akan menghadapi gelombang panas dan berpotensi mencapai suhu 40 hingga 50 derajat celcius?")

st.write("Tidak.")

st.write("Menurut keterangan dari BRIN (Badan Riset dan Inovasi Nasional), cuaca panas di Jakarta hanya termasuk “Hot Spells”, di mana suhu rata-rata berada di atas 28 derajat celcius selama beberapa hari berturut-turut.")

st.write("Berikut adalah tips untuk menghadapi “Hot Spells”:")

st.write("1. Menggunakan pakaian yang longgar dan berbahan ringan.")
st.write("2. Menghindari aktivitas di luar ruangan di siang hari.")
st.write("3. Jika sedang beraktivitas di luar ruangan, bisa mengenakan topi atau memakai payung.")
st.write("4. Menghindari paparan langsung matahari.")
st.write("5. Menjaga stamina dengan mengkonsumsi vitamin dan berolahraga")

st.caption("Source Data : dataonline.bmkg.go.id,https://inet.detik.com/science/d-6697149/pakar-brin-sebut-cuaca-panas-di-indonesia-karena-hot-spells-apa-itu")





